name = "Forge Fun"
author = "Exo"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9abc3d9a5efd5867cdc87dd136acd928c3c93b01168432d5dd6bd7786aedba9b"

[versions]
forge = "36.0.0"
minecraft = "1.16.5"
