name = "Forge Fun"
author = "Exo"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3499480866b44a94ca25fa32afaa3c26666c5b57d06ce598be33f57aa4f614c"

[versions]
forge = "36.0.0"
minecraft = "1.16.5"
