name = "All The Tweaks"
filename = "allthetweaks-1.4.0-1.16.5-36.1.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3328/745/allthetweaks-1.4.0-1.16.5-36.1.13.jar"
hash-format = "murmur2"
hash = "2120265284"

[update]
[update.curseforge]
file-id = 3328745
project-id = 364120
release-channel = "beta"
