name = "ATO - All the Ores"
filename = "alltheores-1.3.5-1.16.5-36.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3394/539/alltheores-1.3.5-1.16.5-36.1.0.jar"
hash-format = "murmur2"
hash = "549028357"

[update]
[update.curseforge]
file-id = 3394539
project-id = 405593
release-channel = "beta"
