name = "CC: Tweaked"
filename = "cc-tweaked-1.16.5-1.97.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3368/207/cc-tweaked-1.16.5-1.97.0.jar"
hash-format = "murmur2"
hash = "743542537"

[update]
[update.curseforge]
file-id = 3368207
project-id = 282001
release-channel = "beta"
