name = "Comforts (Forge)"
filename = "comforts-forge-1.16.5-4.0.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3359/524/comforts-forge-1.16.5-4.0.1.1.jar"
hash-format = "murmur2"
hash = "229097414"

[update]
[update.curseforge]
file-id = 3359524
project-id = 276951
release-channel = "beta"
