name = "Environmental Tech"
filename = "envirotech-1.16.5-3.0.9.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3396/509/envirotech-1.16.5-3.0.9.3.jar"
hash-format = "murmur2"
hash = "3939826390"

[update]
[update.curseforge]
file-id = 3396509
project-id = 245453
release-channel = "beta"
