name = "Exchangers"
filename = "Exchangers-1.16.5-3.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3207/546/Exchangers-1.16.5-3.0.2.jar"
hash-format = "murmur2"
hash = "2485980459"

[update]
[update.curseforge]
file-id = 3207546
project-id = 270183
release-channel = "beta"
