name = "GunpowderLib"
filename = "GunpowderLib-1.16.5-1.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3198/17/GunpowderLib-1.16.5-1.2.2.jar"
hash-format = "murmur2"
hash = "4011725484"

[update]
[update.curseforge]
file-id = 3198017
project-id = 356646
release-channel = "beta"
