name = "McJtyLib"
filename = "mcjtylib-1.16-5.0.21.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3380/980/mcjtylib-1.16-5.0.21.jar"
hash-format = "murmur2"
hash = "2272150536"

[update]
[update.curseforge]
file-id = 3380980
project-id = 233105
release-channel = "beta"
