name = "Refined Storage Addons"
filename = "refinedstorageaddons-0.7.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3065/694/refinedstorageaddons-0.7.2.jar"
hash-format = "murmur2"
hash = "2406152037"

[update]
[update.curseforge]
file-id = 3065694
project-id = 272302
release-channel = "beta"
