name = "RFTools Builder"
filename = "rftoolsbuilder-1.16-3.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3380/279/rftoolsbuilder-1.16-3.1.0.jar"
hash-format = "murmur2"
hash = "82601564"

[update]
[update.curseforge]
file-id = 3380279
project-id = 347706
release-channel = "beta"
