name = "Silent Lib (silentlib)"
filename = "silent-lib-1.16.3-4.9.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3235/738/silent-lib-1.16.3-4.9.6.jar"
hash-format = "murmur2"
hash = "2198738089"

[update]
[update.curseforge]
file-id = 3235738
project-id = 242998
release-channel = "beta"
