name = "/tank/null"
filename = "tanknull-2.3-1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3224/872/tanknull-2.3-1.16.4.jar"
hash-format = "murmur2"
hash = "2026934031"

[update]
[update.curseforge]
file-id = 3224872
project-id = 361246
release-channel = "beta"
