name = "The Twilight Forest"
filename = "twilightforest-1.16.5-4.0.490-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3334/287/twilightforest-1.16.5-4.0.490-universal.jar"
hash-format = "murmur2"
hash = "3203458263"

[update]
[update.curseforge]
file-id = 3334287
project-id = 227639
release-channel = "beta"
