name = "Thermal Foundation"
filename = "thermal_foundation-1.16.4-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3248/150/thermal_foundation-1.16.4-1.2.0.jar"
hash-format = "murmur2"
hash = "3592131153"

[update]
[update.curseforge]
file-id = 3248150
project-id = 222880
release-channel = "beta"
