name = "U Team Core"
filename = "u_team_core-1.16.5-3.2.1.196.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3350/619/u_team_core-1.16.5-3.2.1.196.jar"
hash-format = "murmur2"
hash = "1589661685"

[update]
[update.curseforge]
file-id = 3350619
project-id = 273744
release-channel = "beta"
