name = "ValkyrieLib"
filename = "valkyrielib-1.16.5-3.0.9.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3396/151/valkyrielib-1.16.5-3.0.9.2.jar"
hash-format = "murmur2"
hash = "1666450261"

[update]
[update.curseforge]
file-id = 3396151
project-id = 245480
release-channel = "beta"
